# Generated by Django 5.1.3 on 2024-12-08 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_purchasemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='buyers',
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_of_car', to='Car.carmodel'),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
